version: '3.8'

services:
  db:
    image: postgres:15
    container_name: repstorage-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: repstorage
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./application
    container_name: repstorage-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/repstorage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      STORAGE_STRATEGY: file-system
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
